basePath: /api/v1
definitions:
  handler.ErrorResponse:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  request.RegisterPixKeyRequest:
    properties:
      accountHolderLastName:
        type: string
      accountHolderName:
        type: string
      accountNumber:
        type: integer
      accountType:
        type: string
      agencyNumber:
        type: integer
      pixKey:
        type: string
      pixKeyType:
        type: string
    required:
    - accountHolderName
    - accountNumber
    - accountType
    - agencyNumber
    - pixKey
    - pixKeyType
    type: object
  response.RegisterPixKeyResponse:
    properties:
      accountHolderLastName:
        type: string
      accountHolderName:
        type: string
      accountNumber:
        type: integer
      accountType:
        type: string
      agencyNumber:
        type: integer
      id:
        type: string
      pixKeyType:
        type: string
      response:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: danilo.kodavara@gmail.com
    name: Danilo Kodavara
    url: https://www.linkedin.com/in/danilo-kodavara/
  description: API para cadastro de chave pix
  license:
    name: Danilo  Kodavara License
    url: https://www.linkedin.com/in/danilo-kodavara/
  termsOfService: http://swagger.io/terms/
  title: Cadastro de Chave Pix API
  version: v1
paths:
  /pix-keys:
    post:
      consumes:
      - application/json
      description: Register Pix Key
      parameters:
      - description: Pix Key Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.RegisterPixKeyRequest'
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.RegisterPixKeyResponse'
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/handler.ErrorResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/handler.ErrorResponse'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Register Pix Key
      tags:
      - pix-keys
  /pix-keys/{key}:
    get:
      consumes:
      - application/json
      description: Find PixKey By Key
      parameters:
      - description: Pix Key
        in: path
        name: key
        required: true
        type: string
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.RegisterPixKeyResponse'
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/handler.ErrorResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/handler.ErrorResponse'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Find PixKey By Key
      tags:
      - pix-keys
swagger: "2.0"
